spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://eureka2:8762/eureka/,http://eureka1:8761/eureka/
---
spring:
  profiles: eureka1
server:
  port: 8761
eureka:
  instance:
    hostname: eureka1
---
spring:
  profiles: eureka2
server:
  port: 8762
eureka:
  instance:
    hostname: eureka2

management:
  endpoints:
    web:
      exposure:
        # 开放所有监控端点
        include: "*"
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: always