server:
  port: 8006

spring:
  application:
    name: hystrix-turbine
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/
  instance:
    prefer-ip-address: true
turbine:
  # 要监控的微服务列表，多个用,分隔
  appConfig: user-server,movie-server
  clusterNameExpression: "'default'"
